# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('clients', '0002_client_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='subtotal')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='ip')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='producto')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
