# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-04 19:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(default=datetime.datetime(2016, 5, 4, 19, 26, 4, 255230, tzinfo=utc), max_length=255, verbose_name='apellido'),
            preserve_default=False,
        ),
    ]
