# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 05:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20160504_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(default=datetime.datetime(2016, 5, 6, 5, 35, 40, 198624, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
