# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='celphone',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
