# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_celphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='celphone',
            field=models.IntegerField(null=True),
        ),
    ]
