# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-24 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20160524_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
