# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('PR', 'Proceso'), ('EN', 'Entregado'), ('CA', 'Cancelado'), ('AB', 'Cancelado')], max_length=2, verbose_name='estado')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio total')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='fecha')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='cliente')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
