# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_ordersdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='ordersdetail',
            old_name='subtotal_price',
            new_name='subtotal_amount',
        ),
    ]
