# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160524_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deliver_date',
        ),
    ]
