# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-03 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nombre')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('category', models.CharField(choices=[('GS', 'Gaucho simple'), ('GS2', 'Gaucho simple de dos colores'), ('GD', 'Gaucho doble'), ('GD3', 'Gaucho doble de tres colores')], max_length=255, verbose_name='categoria')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='precio')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='imagen')),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
