# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20160427_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GS', 'Gaucho simple'), ('GS2', 'Gaucho simple de dos colores'), ('GD', 'Gaucho doble'), ('GD3', 'Gaucho doble de tres colores')], max_length=255, verbose_name='categoria'),
        ),
    ]
